server:
  port: 8888
  
spring:
  cloud:    config:      server:        git:          uri: https://github.com/Diegobraun/microservice-repo
          search-paths: fornecedor, loja, transportador
          default-label: main